GET http://localhost:5000/products

###
GET http://localhost:5000/products/3

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "product 3",
    "price": 3000
}

###
PATCH http://localhost:5000/products/3
Content-Type: application/json

{
    "name": "product 3 update",
    "price": 5000
}

###
DELETE http://localhost:5000/products/3

